spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  security:
    filter:
      order: -100
  mail:
    host: smtp.qq.com
    username: 2469623748@qq.com
    password: YYYXYTXKERMDSLD
  rabbitmq:
    addresses: localhost
    username: admin
    password: admin

